### ISSUE TITLE
lasttime queries not correct?

### ISSUE THREAD

**Issue by aeppert** [jmdevince/cifpy3#29]
I am attempting to query using with the lasttime attribute as an additional constraint. 

Long story, short, I want to return data only in the last 5days, not over the 60-days worth of indices I am keeping. It does not appear that out of the box CIFpy3 is using this field appropriately, or I am simply not understanding it.

Any insights would be greatly appreciated.

**Comment by jmdevince** [comment]
Can you provide the query string you're using to search?

**Comment by jmdevince** [comment]
It's been over 60 days without a reply. Closing.
