### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by Danko90** [jmdevince/cifpy3#4]
Hello,
Congratulation for the great job.

I tried to install the CIF but it didn't work.
When I try to download the install.sh I get 404 error, so I downloaded the project through git and when I run install.sh, it seems work but I don't see the directory inside /opt/ as written in the documentation.

Can you help me?

Thank you

Danilo

**Comment by jmdevince** [comment]
I can, let me do some work on finishing the install script as well as getting some init scripts created. Those are (kind of) the last pieces of the puzzle. I still need to add the ability to add/remove tokens via the CLI. right now you can only do it via the REST API.

**Comment by jmdevince** [comment]
Okay, the installation script for Debian is fixed. The API is still not 100% complete nor is the cif-utility program. 

I'm going to check if it works with Ubuntu and CentOS/RHEL next.

**Comment by Danko90** [comment]
Thank you! 
I'll help you in the next issues!
