### ISSUE TITLE
KeyError: 'feeds'

### ISSUE THREAD

**Issue by Danko90** [jmdevince/cifpy3#7]
Hello,

I just updated your changes, but I got this error in the feeder.py:

Traceback (most recent call last):
  File "./cif-server", line 145, in <module>
    feeder = cif.feeder.Feeder()
  File "/root/packages/cifpy3/lib/cif/feeder/feeder.py", line 18, in __init__
    self.load_feeds()
  File "/root/packages/cifpy3/lib/cif/feeder/feeder.py", line 37, in load_feeds
    for feed_name in feeds[feed_file].feed_config['feeds'].keys():
KeyError: 'feeds'

on the line:
for feed_name in feeds[feed_file].feed_config['feeds'].keys():

I don't understand to fix it. Could you help me?

Thanks

**Comment by jmdevince** [comment]
Pulling the latest version should fix that.

**Comment by Danko90** [comment]
it still doesn't work, same error.

**Comment by jmdevince** [comment]
It looks like you're missing the 'feeds' section from one of the config files.

**Comment by Danko90** [comment]
Resolved.
You should add 

if "feeds" in feeds[feed_file].feed_config:

before that for.

**Comment by Danko90** [comment]
Probably, I'll check it!
Thank you

**Comment by jmdevince** [comment]
I thought I had. I will add that.
